.github/workflows/tests.yml, README.md
=> Github Actions Forge Tests

LICENSE-APACHE, LICENSE-MIT
=> chore: add license

src/Vm.sol
see https://github.com/gakonst/foundry/pull/725 for more info
=> chore: add `assume` cheat code

src/test/StdStorage.t.sol
Reverts brockelmore/forge-std#18 per feedback on https://github.com/brockelmore/forge-std/pull/19
=> Revert "fix: remove public from constructor"

README.md, src/console.sol
Just added the console contract from the forge README. Not sure about the licensing here, if it needs change
=> Streamlined console log functionality with forge

src/Vm.sol
Added in https://github.com/gakonst/foundry/pull/918
=> Allow calling expectRevert without any arguments

README.md
There are multiple broken parts of the `StdStorage` README samples.
Implemented and tested changes here: https://github.com/abigger87/stdtests
Example:
=> docs: StdStorage Readme Examples Broken

README.md, src/Test.sol, src/console2.sol
See https://github.com/foundry-rs/foundry/pull/1367 for details
=> feat: add console2.sol

src/Vm.sol
Add `expectEmit(bool,bool,bool,bool,address)` signature to `Vm` interface
=> chore(vm): add alt `expectEmit` signature

src/Test.sol, src/test/StdCheats.t.sol
Resolves: #63 
add `changePrank` cheat
```solidity
function testChangePrank() public {
vm.startPrank(address(1337));
doStuff();
changePrank(address(0xdead));
doStuffAsDead();
changePrank(address(1337));
doStuff();
vm.stopPrank();
}
```
cc: @paulrberg
=> feat(cheats): add `changePrank`

src/Test.sol, src/test/StdCheats.t.sol
Resolves #35
Added checks for `zero` address reverts.
cc: @mds1
=> feat(tests): add check for successful `deployCode`.

src/Vm.sol
Pending https://github.com/foundry-rs/foundry/pull/1208
=> add `broadcast` cheatcodes

src/Vm.sol
Update `Vm.sol`. See https://github.com/foundry-rs/foundry/pull/1744.
Add the new `env` cheatcodes to `Vm`.
=> ✨ Add env cheatcodes to Vm

src/Test.sol, src/test/StdAssertions.t.sol
@ZeroEkkusu likely won't be able to get to the tests today so if wanted to fix those that would be appreciated!
cc @paulrberg
=> ♻️ Simplify assertEq for arrays

.gitignore, src/Vm.sol
was going through book docs for new cheatcodes and saw some grammar issues in the comments
book issue: https://github.com/foundry-rs/book/issues/371
=> ✏️ Fix typos in Vm

src/Vm.sol
Ref https://github.com/foundry-rs/foundry/pull/2161
=> feat: add log cheatcodes and types

src/Vm.sol
Ref https://github.com/foundry-rs/foundry/pull/2127
=> feat: add toString cheatcodes

src/Vm.sol
Adds new cheatcodes introduced in https://github.com/foundry-rs/foundry/pull/1715
=> feat: add new fork + snapshot cheatcodes

src/Vm.sol
Add `vm.deriveKey` cheatcodes (from https://github.com/foundry-rs/foundry/pull/2299), similar to #112!
=> feat: add deriveKey cheatcodes

src/Vm.sol
=> Add new fork-related cheatcodes to Vm.sol

src/Vm.sol
ref https://github.com/foundry-rs/foundry/pull/2762
=> feat: add projectRoot cheatcode to Vm.sol

README.md
Fix https://github.com/foundry-rs/forge-std/issues/132
Clarify licensing in readme.
=> docs: add license info

src/test/StdAssertions.t.sol
Ref https://github.com/foundry-rs/foundry/pull/2929#issuecomment-1227667978
=> test: more robust tests by removing strict assumes

src/Vm.sol
Ref https://github.com/foundry-rs/foundry/pull/2854
=> feat: add parsing cheat codes

src/Script.sol, src/Vm.sol, src/test/Script.t.sol
Re https://github.com/foundry-rs/foundry/pull/3047/
=> feat: add rememberKey cheat code

src/Vm.sol
Re https://github.com/foundry-rs/foundry/pull/3111
=> feat: add broadcast and startBroadcast private key overloads

LICENSE-APACHE, LICENSE-MIT
Sorry @brockelmore, nothing personal 😝
Phrasing based off https://www.linuxfoundation.org/blog/copyright-notices-in-open-source-software-projects/
=> chore: update license

src/Vm.sol
Add new `getDeployedCode` cheatcode
book https://github.com/foundry-rs/book/pull/624
foundry: https://github.com/foundry-rs/foundry/pull/3248
=> feat: add getDeployedCode cheatcode

src/Vm.sol
book: https://github.com/foundry-rs/book/pull/654
foundry: https://github.com/foundry-rs/foundry/pull/3328
=> feat: add transact cheatcode

src/StdCheats.sol
`forge fmt` has been updated. CI failing.
Run `forge fmt`.
=> chore: `forge fmt`

foundry.toml, src/StdCheats.sol, test/StdCheats.t.sol
Fixes https://github.com/foundry-rs/forge-std/issues/224
=> fix: swap default mainnet RPC URL

package.json
For https://github.com/foundry-rs/forge-std/issues/233
=> chore: bump version to v1.1.1

src/Common.sol
=> feat: add common addresses

src/interfaces/IERC1155.sol, src/interfaces/IERC165.sol, src/interfaces/IERC20.sol, src/interfaces/IERC4626.sol, src/interfaces/IERC721.sol
=> ♻️ chore: add MIT license to interfaces

src/Vm.sol
Ref https://github.com/foundry-rs/foundry/pull/3717
=> chore: add fsMetadata cheat

package.json
Fixes https://github.com/foundry-rs/forge-std/issues/219
=> chore: bump version to v1.2.0 (the upcoming release)

src/StdStorage.sol
Logically equivalent but more succinct, and clearer.
=> refactor: use simple revert instead of "require(false"

src/Base.sol
See @mds1's [multicall](https://github.com/mds1/multicall).
=> feat: add MULTICALL3_ADDRESS in CommonBase

src/Vm.sol
Should be merged after https://github.com/foundry-rs/foundry/pull/4061
=> feat: parseJSON cheatcodes with type coercion

src/InvariantTest.sol
Just a minor change to stay consistent with the helpful comment, groups user called and foundry called functions together
=> Just a minor change to stay consistent with the helpful comment

foundry.toml, src/StdChains.sol, test/StdChains.t.sol
See https://github.com/foundry-rs/foundry/pull/4175, will merge once CI passes
=> ci: remove key that doesn't work

src/StdInvariant.sol, src/Test.sol
=> refactor(breaking): rename InvariantTest to StdInvariant and have Test inherit from it by default

src/StdJson.sol
=> chore: use coercion cheatcodes with stdJson helpers

src/StdAssertions.sol
=> Bump ds-test and complete assertion log renaming

src/StdChains.sol
Renamed `initialize` to `initializeStdChains()` as  its having conflicts with our proxy contracts in tests when doing an update on  forge-std and also as `initialize` is a quite common name to get collisions.
Fixes #286
=> fix: initialize function collision

src/Vm.sol
add `mockCallRevert` cheatcode to `Vm.sol`
=> add `mockCallRevert` cheatcode

src/StdUtils.sol
Addresses https://github.com/foundry-rs/forge-std/issues/349.
=> refactor: provide pure bound int

src/StdChains.sol
The current writing is a bit unclear and repetitive.
=> docs: improve writing in StdChains comments

src/Vm.sol
Adding `vm.breakpoint()`
ref: https://github.com/foundry-rs/foundry/pull/4679#issuecomment-1517980756
=> (feat) add breakpoints cheatcode

src/Vm.sol
Closes #365
Refs https://github.com/foundry-rs/foundry/pull/4803
=> feat: update fs cheatcodes

foundry.toml, src/StdChains.sol, test/StdChains.t.sol
Ref https://github.com/foundry-rs/foundry/pull/4781
=> chore: update infura keys

src/Vm.sol
Must be merged after https://github.com/foundry-rs/foundry/pull/4770
=> feat(Vm.sol): add `getLabel` cheatcode

src/Vm.sol
Follow up to https://github.com/foundry-rs/foundry/pull/4856
=> feat(cheatcodes): Add `vm.prevrandao` to `Vm.sol`

src/Vm.sol
Complementary pr for foundry-rs/foundry#4884
=> feat: add CallerMode enum and readCallers cheat code

.github/workflows/ci.yml
Realized the indentation was off in #403 so CI didn't run properly, ref https://github.com/foundry-rs/forge-std/actions/runs/5369513873
=> ci: fix indentation

src/StdChains.sol
Adds moonbeam, moonriver and moonbase into StdChains.sol
=> Add support for moonbeam.network chains

src/Vm.sol
https://github.com/foundry-rs/foundry/pull/5613
Closes #432
=> feat: `copyFile` cheatcode

src/Vm.sol
This adds the createWallet functionality introduced in https://github.com/foundry-rs/foundry/pull/5332.
This also adds the `sign()` and `getNonce()` functions for wallets as well.
=> chore(`vm`): add createWallet() for Wallet struct

src/Vm.sol
ref : https://github.com/foundry-rs/foundry/blob/bff4ed912bb023d7bf9b20eda581aa4867a1cf70/testdata/cheats/Vm.sol#L139
=> Update Vm.sol with tryFfi

src/StdInvariant.sol
See https://github.com/foundry-rs/foundry/pull/5605
=> feat: invariant target interfaces

src/Vm.sol
Same as https://github.com/foundry-rs/forge-std/pull/447 for `parseJsonKeys`.
=> perf: mark parseJsonKeys as pure

src/Vm.sol, test/Vm.t.sol
Closes https://github.com/foundry-rs/forge-std/issues/463
@PaulRBerg would appreciate a quick review here if you have the time! No rush though, I also need to give it a review myself before merging
cc @vdrg too since you're also big consumers of Vm, in case this affects you in any way (though it shouldn't affect you)
=> chore: reorder Vm for logical consistency

package.json
Closes https://github.com/foundry-rs/forge-std/issues/467 by updating the package.json to match the upcoming release
=> build: sync package.json version with release version

test/StdCheats.t.sol
=> fix: test naming

src/StdCheats.sol, src/StdUtils.sol, src/Vm.sol, test/Vm.t.sol
As mentioned in https://github.com/foundry-rs/foundry/issues/6270#issuecomment-1810429601, updating Vm.sol and use vm call in `StdUtils`.
=> feat: update `computeCreateAddress`

src/Vm.sol
See https://github.com/foundry-rs/foundry/pull/6545
=> Update vm.sol with changes to AccountAccessKind

src/Vm.sol, test/Vm.t.sol
ref https://github.com/foundry-rs/foundry/pull/6548
=> feat: add new snapshot cheatcodes

scripts/vm.py, src/Vm.sol, test/Vm.t.sol
Ref https://github.com/foundry-rs/forge-std/pull/496#issuecomment-1894700062
Supersedes https://github.com/foundry-rs/forge-std/pull/496
=> fix: don't hardcode string values in Vm generator

src/Vm.sol, test/Vm.t.sol
=> Add `stopExpectSafeMemory`

.github/workflows/ci.yml, .github/workflows/sync.yml
Supercedes https://github.com/foundry-rs/forge-std/pull/533 with a smaller set of changes
=> ci: modernize workflows

src/Vm.sol, test/Vm.t.sol
Supercedes https://github.com/foundry-rs/forge-std/pull/546 and https://github.com/foundry-rs/forge-std/pull/539
=> feat: add all new cheats to interface

src/Vm.sol, test/Vm.t.sol
=> add: blobhashes cheats

package.json
Closes https://github.com/foundry-rs/forge-std/issues/534
=> chore: bump to v1.8.2

src/StdChains.sol, test/StdChains.t.sol
- feat: add blast goerli & blast chaindata setup
=> Feat: add blast goerli & blast chaindata setup

src/StdInvariant.sol
`excludeSelector` added in forge with https://github.com/foundry-rs/foundry/pull/8185
=> feat: add invariant excludeSelector helper

src/Vm.sol, test/Vm.t.sol
Ref https://github.com/foundry-rs/foundry/pull/7960
=> feat: update vm interface with new cheats

src/Vm.sol, test/Vm.t.sol
new cheatcode added in https://github.com/foundry-rs/foundry/pull/8750
=> Add resetGasMetering and expectPartialRevert cheatcodes

README.md, src/StdCheats.sol, src/interfaces/IERC4626.sol
Hello
I found and fixed several spelling issues in order to ensure a better understanding.
Br, Elias.
=> docs fix spelling issues

package.json, src/Vm.sol, test/Vm.t.sol
Adds the cheatcodes added in: https://github.com/foundry-rs/foundry/pull/8952
Book documentation added here: https://github.com/foundry-rs/book/pull/1323
=> feat: add gas snapshot cheatcodes

src/interfaces/IERC6909.sol
Closes #655 adding ERC 6909 interface
=> ERC-6909 interface

src/StdChains.sol
=> chore(StdChains): add hoodi testnet

src/Vm.sol, test/Vm.t.sol
- update vm.deployCode sigs: https://github.com/foundry-rs/foundry/pull/10178
- update vm.signAndAttachDelegation and vm.signDelegation sigs: https://github.com/foundry-rs/foundry/pull/10182
- update vm.setArbitraryStorage sig: https://github.com/foundry-rs/foundry/pull/10219
- add new vm.shuffle and vm.sort: https://github.com/foundry-rs/foundry/pull/10187
=> feat: update cheatcodes

src/Vm.sol, test/Vm.t.sol
- add `vm.interceptInitcode` https://github.com/foundry-rs/foundry/pull/10242
=> add intercept create cheatcode

src/Vm.sol, test/Vm.t.sol
ref https://github.com/foundry-rs/foundry/pull/10518
ref https://github.com/foundry-rs/foundry/pull/10370
=> add stopRecord and 7702 cross chain cheatcodes

README.md
The forge-std link is broken in the README
=> Broken forge link

src/StdAssertions.sol
Fixes https://github.com/foundry-rs/forge-std/issues/583.
=> fix: re-add fail(string)

package.json
Bumps `package.json` for next 1.11.0 release
=> feat: release 1.11.0
