foundry-rs/forge-std

- src/stdlib.sol
- src/test/StdCheats.t.sol
- Adds `skip` and `rewind` stdcheats. Saw these mentioned in the foundry telegram and know others who have requested them, so figured I'd PR them in
- Also removed an unnecessary cast when computing the cheat code address
> Time cheatcodes

- src/stdlib.sol
- src/test/StdCheats.t.sol
Adds helpers to make deployment using `vm.getCode` easier. At some point I would like to add a third overload where you can specify the address that the contract will be deployed at, but I think this will require some extra functionality to make constructors work properly.
> add deployCode helper

- src/test/StdStorage.t.sol
Fixes this warning
```
Warning: Visibility for constructor is ignored. If you want the contract
to be non-deployable, making it "abstract" is sufficient.
-->
/Users/rootulp/git/rootulp/forge-std/src/test/StdStorage.t.sol:252:5:
|
252 |     constructor() public {
|     ^ (Relevant source part starts here and spans across multiple
lines).
```
> fix: remove public from constructor

- src/stdlib.sol
- src/test/StdCheats.t.sol
Gm! This is a new `tip` stdcheat.
Simplify funding an account with a set amount of an arbitrary ERC20 token.
A convenient solution you can use in tests:
```solidity
tip(alice, 10000e18, dai);
// Let's test it
assertEq(daiToken.balanceOf(alice), 10000e18); // [PASS]
```
Especially useful when forking.
Edit: Need to make a few changes to make it work with ~~every~~ a majority of tokens. **✔️ DONE**
> feat: add `tip` stdcheat

- README.md
The intent of this pr is to fix a mistake in the first coding example:
```
contract TestContract is DSTest, stdError {
```
No need to import stdError, and doing so throws:
Also, while I had the readme open I cleaned up a few very minor spelling/grammar things.
> fix: updates coding example and minor spelling/grammar fixes

- src/stdlib.sol
- src/test/StdError.t.sol
Cover `INVALID opcode` cases, such as trying to directly access an element of an array in another contract that is oob, or when there was an error while decoding the error message (`0x`).
```solidity
contract C {
bool[] public bools;
constructor() {
bools.push(true);
}
}
contract TestC is DSTest {
function testLowLevelError() public {
Vm vm = Vm(HEVM_ADDRESS);
C c = new C();
// P.S. No, we cannot use `indexOOBError` here
vm.expectRevert(stdError.lowLevelError);
c.bools(1);
}
}
```
<br>
Add a test for `encodeStorageError`. This was marked as `TODO`.
```solidity
/// INSIDE TESTING CONTRACT
function testExpectEncodeStg() public {
vm.expectRevert(stdError.encodeStorageError);
test.encodeStgError();
}
/// INSIDE DUMMY CONTRACT
bytes someBytes;
function encodeStgError() public {
assembly { …
```
> 2 commits: `lowLevelError` + `testExpectEncodeStg`

- src/stdlib.sol
Does anyone use these?
```solidity
abstract contract stdCheats {
Vm constant vm_std_cheats = Vm(address(uint160(uint256(keccak256('hevm cheat code')))));
StdStorage std_store_std_cheats;
```
Let's make them private so they don't pop up as suggestions (autocomplete). Better UX.
> fix(stdlib): make variables not meant for end-users `private`

- src/stdlib.sol
fixes proxy handling by correctly handling reverting + low byte length returns
> fix stdstorage return handling

- README.md
- src/Test.sol
- src/test/StdCheats.t.sol
- src/test/StdError.t.sol
- src/test/StdStorage.t.sol
Instead of having to do multiple imports, we now have a canonical `import forge-std/Test.sol` which is inherited from as `contract MyTest is Test`.
Test.sol now contains:
1) Cheatcodes under `vm`
2) all ds-test assert/log emits because it inherits from `DSTest`
3) console.log because it now imports it
4) `stdstore` which is made available by doing `using stdStorage for StdStorage` because libraries are not inherited (https://ethereum.stackexchange.com/a/98923)
This improves testing UX a lot, as you don't need to really remember any special imports or magic variables. You just import `Test` and you're g2g.
```solidity
pragma solidity 0.8.10;
import "forge-std/Test.sol";
contract ContractTest is Test {
function testExample() public {
vm.roll(100);
console.log(1);
emit log("hi"); …
```
> Improve stdlib import ergonomics

- README.md
Docs are ready!
Should we mention it *here* in the readme?
**Other:**
- Added `Std Assertions` section to the readme with a brief description
- Suggestion: we should change the repo description to something like `Forge Standard Library is a collection of helpful contracts that make writing tests easier, faster, and more user-friendly.` (put "Foundry" somewhere in there) - to be concise
> docs: add forge std guide mention

- src/Test.sol
Fixes #53 
- Removes `unchecked` to keep `0.6.0` compatibility
- Hardcodes case for `a = type(int256).min`
Unfortunately, I can't do something like:
```
if (a == type(int256).min)
return  type(int256).max + 1;
```
Since `type()` was introduced in [Solidity `0.6.8`](https://github.com/ethereum/solidity/releases/tag/v0.6.8)
If you want to use `type()`, you can bump the min version for this package to `0.6.8`
> Fix STD-Math 0.6.0 compatibility

- .github/workflows/tests.yml
- src/test/StdAssertions.t.sol
- src/test/StdCheats.t.sol
- src/test/StdError.t.sol
- src/test/StdMath.t.sol
- src/test/StdStorage.t.sol
Fixes #55
Update the CI to additionally build the `Test` contract with solc versions `0.8.0`, `0.7.0`, `0.6.0`.
This will prevent us from accidentally breaking compatibility with older Solidity versions in the future.
> build: check compatibility with older solc versions

- src/Test.sol
- src/test/StdCheats.t.sol
Added ```bound``` from Solmate and added the associated tests from the repo as well. All ```testFail``` style tests were updated to ```expectRevert``` and an additional test for ```type(uint256).max``` as the upper bound was also added to test edge case.
Closes #48
> feat: upstream Solmate's bound 

- src/Test.sol
Fix `Test.sol` compatibility with Solidity version `0.6.0`.
> fix(test): hardcore `type(uint256).max` value

- src/Test.sol
Reverts foundry-rs/forge-std#66
The above broke compilation on older solc versions
> Revert "Add non-reentrant comment to remove reentrancies detected by Slither"

- src/Test.sol
- src/test/StdAssertions.t.sol
This is a small extension of the current set of assertions. I've added `fail(string)`  to provide a clean and readable way to fail tests if a certain branch or execution point is hit
> feat(assertions): add `fail(string)` that logs fail reason

- src/Vm.sol
Added overloaded `mockCall` and `expectCall` methods with additional `msg.value` parameter as implemented in foundry-rs/foundry#1619
> feat(cheats): add overloaded `mockCall` and `expectCall` cheatcodes

- src/Test.sol
- src/test/StdStorage.t.sol
Resolve #65 
Add the following terminator functions to `StdStorage`:
- `read_bytes32`
- `read_bool`
- `read_address`
- `read_uint`
- `read_int`
The naming style follows the DSTest convention (`_<type>`, such as `log_address`).
```solidity
// BEFORE
uint256 slot = stdstore
.target(address(c))
.sig(c.a.selector)
.find();
bytes32 val = vm.load(address(c), bytes32(slot));
address a = address(uint160(uint256(val)));
// NOW
address a = stdstore
.target(address(c))
.sig(c.a.selector)
.read_address();
```
Cc @itamarreif
And also let's discuss whether this is the right solution.
> feat(storage): add `read` functions

- src/Test.sol
This PR resolves the issues raised here: https://github.com/foundry-rs/forge-std/pull/71#issuecomment-1128730537
Have elected not to delete the tests as a regression guard (the tests implement keccak256 over the inputs so this is a nice protection against any accidental breakage in the future). That said, obviously your call on what the end codebase looks like
> refactor(asserts): delegate assertEq(bytes) to ds-test

- .gitignore
- src/Script.sol
Hotfix compatibility issues with solc versions `<0.8.0` introduced in https://github.com/foundry-rs/forge-std/commit/cc2dee26166823ccfe1c1b928776ee340095372b.
Move the constant `VM_ADDRESS` in `Script.sol` to contract `Script`.
> 🚑️ Fix compatibility with older solc

- src/Test.sol
- src/test/StdAssertions.t.sol
I didn't add an overloaded function with an `err` argument because I couldn't decide where to emit the custom error string: in the array length comparison check, in the per-element comparison check, or as a third argument to the `assertEq` function.
> ✨ Add assertEq for uint and int arrays

- src/Test.sol
New logs, besides those from DSTest, are available. See https://github.com/foundry-rs/forge-std/pull/85 and https://github.com/foundry-rs/foundry/pull/1916.
Group the new logs under a dedicated header `STD-LOGS`.
Also: misc fixes
> ♻️ Group Std Logs

- src/Script.sol
This will be used by forge to ignore checking contract size for scripts. Currently `forge build --sizes` will error if a script exceeds the size limit so we'll update it to ignore contracts with `IS_SCRIPT`. This means test contracts will have both `IS_SCRIPT = true` and `IS_TEST = true`, which I think is ok to keep this simple, and just means that `IS_TEST` takes priority over `IS_SCRIPT`
cc @gakonst
> feat: add IS_SCRIPT to know if a contract is a script

- src/Vm.sol
With File I/O capability in place, this PR adds the associated cheat codes to `Vm.sol`
> Add interfaces for File I/O cheatcodes to Vm.sol

- src/Test.sol
bound() needs to be virtual for Test to be compatible to be extended together with DSTestPlus of solmate
> refactor: make `bound` `internal virtual`

- src/Test.sol
- src/test/StdAssertions.t.sol
Just like https://github.com/foundry-rs/forge-std/pull/85 but now for `address[]` arrays.
I have written tests this time 😅
> feat: add `assertEq` for `address` arrays

- src/Test.sol
- src/test/StdStorage.t.sol
Improve DX.
Reading a value with Std Storage's `read_bool` reverts if the read bytes cannot be decoded to `bool`.
No explanation is provided to the dev as to what and why reverted, which is frustrating.
Revert manually with  `stdStorage find(StdStorage): Cannot decode. Make sure you are reading a bool.`.
> 🧑‍💻 Add explanation why read_bool reverted

- src/Test.sol
I don't see any downside in marking this constant as `internal` rather than `private`.
I actually wanted to use it in my contracts when I realized that I can't use it.
> Mark UINT256_MAX as internal

- src/Test.sol
The unary minus operator `-` can be applied to `0`.
> Use > operator instead of >= in abs

- src/Test.sol
See [this](https://twitter.com/PaulRBerg/status/1546957951579062272).
I was also thinking to add a comment to explain why `(a^b)>-1` works - WDYT?
> Optimize same sign check

- src/Vm.sol
Not sure if this was intentional or not, but if it wasn't, I think it'd be worth it to also bound the pragma in the `VM` contract, for consistency purposes.
> Bound pragma version in Vm.sol

- LICENSE-APACHE
- LICENSE-MIT
- README.md
- src/Script.sol
- src/Test.sol
- src/Vm.sol
- src/test/Script.t.sol
- src/test/StdAssertions.t.sol
- src/test/StdCheats.t.sol
- src/test/StdError.t.sol
- src/test/StdMath.t.sol
- src/test/StdStorage.t.sol
The licenses provided in the repo are [MIT](https://github.com/foundry-rs/forge-std/blob/f32dbdc3f014176539d95099cbe617968fd0b059/LICENSE-MIT) and [Apache 2.0](https://github.com/foundry-rs/forge-std/blob/master/LICENSE-APACHE), but in the Solidity files the identifier used is `Unlicense`:
https://github.com/foundry-rs/forge-std/blob/f32dbdc3f014176539d95099cbe617968fd0b059/src/Test.sol#L1
However, if that was intentional, I would still hold it that it would be a good idea to switch over to `MIT`, due to the reasons given in this [Reddit post](https://www.reddit.com/r/github/comments/hvp4k6/whats_the_difference_between_mit_and_unlicense/). Here's a Reddit user explaining the legal questionability of the `Unlicense` license:
> In a few jurisdictions (iirc Germany),they are not legally …
> Set SPDX identifier to MIT in Solidity files

- src/Test.sol
- src/test/StdCheats.t.sol
As per the discussion in https://github.com/foundry-rs/forge-std/pull/119, this PR marks all cheats as `internal`.
I have not marked the PR as ready for review though, because there's one test that is not passing anymore, `testDeployCodeFail`. The reason for that is that instead of `this.deployCode`, the test now calls just `deployCode`. This definitely has something to do with the `getCode` cheatcode which expects a relative path, but I'm not sufficiently familiar with the cheatcodes environment to know how to fix this.
**Update**: fixed this in https://github.com/foundry-rs/forge-std/pull/121/commits/190f5a19372f1b79116886ebf2fc02bd97458495. PR ready for review now.
> Mark all cheats as "internal" (WIP)

- src/Test.sol
- src/test/StdCheats.t.sol
Before, we couldn't use the `deployCode` cheatcode with value on contract construction.
This PR is a fix for: https://github.com/foundry-rs/forge-std/issues/131
A little PoC was done here: https://github.com/iFrostizz/deployCodeVal
> feat: `deployCode` with value

- src/Test.sol
- src/test/StdCheats.t.sol
Two small quality-of-life functions to easily create labeled addresses.
Inspired by https://twitter.com/eth_call/status/1549792921976803328
Addresses https://github.com/foundry-rs/forge-std/issues/135
> feat: makeAddr and makeAddrAndKey

- src/Test.sol
`err` message was not passed to `assertEq` in `assertApproxEqRel` method. These two methods are equivalent when `maxPercentDelta` is zero.
> assertApproxEqRel error message on zero delta

- src/Assertions.sol
- src/Cheats.sol
- src/Script.sol
- src/Storage.sol
- src/Utils.sol
- src/Vm.sol
- src/test/StdCheats.t.sol
Fix #78 
**Note**: Merging into `v0.3`
- Add `stdStorageSafe` without `checked_write`
- Add `CheatsSafe` with only `deployCode`
- Add `VmSafe` with only read-only cheatcodes
- Update `Script`
- Make all components `abstract`
- Update `deployCode` tests
- `stdStorage` delegates some functions to `stdStorageSafe`. This solution works for Solidity 0.6.0 and requires minimal code duplication:
```solidity
stdStorageSafe {
safeFun() {
implementation
}
}
stdStorage {
safeFun() {
return stdStorageSafe.safeFun()
}
unsafeFun() {
implementation
}
}
```
- Interfaces cannot inherit in Solidity 0.6.0, so, `VmSafe` contains duplicate code. Someone should check if I removed any necessary cheatcodes in `VmSafe`.
- Only Cheats from `CheatsSafe` will be accessible in `Script` by default
- Only cheatcodes …
> feat: make `Script` safer

- src/Vm.sol
Ref https://github.com/foundry-rs/foundry/pull/3011
Leaving as draft until that PR is merged/released
> fix: remove bit size suffixes from parse cheats

- src/Test.sol
follow solc's suggestions and
* add `pure` restriction where possible
* explicitly return transaction
cc @odyslam
> chore: get rid of some warnings

- foundry.toml
- src/Test.sol
- src/test/StdAssertions.t.sol
- src/test/StdCheats.t.sol
- Fixes #165 
- Adds `foundry.toml` to address latest `allowed_paths` error that originates from https://github.com/foundry-rs/foundry/pull/3007
> feat: add more uint assertions

- package.json
Adds a package.json file so forge-std can be properly imported as a git dependency.
> feat: add package.json

- src/Vm.sol
Ref https://github.com/foundry-rs/foundry/pull/3262
> feat: add new fork cheatcodes

- src/Vm.sol
Ref https://github.com/foundry-rs/foundry/pull/3429
> feat: add cheats to read/write binary files

- src/StdUtils.sol
- src/interfaces/IERC1155.sol
- src/interfaces/IERC165.sol
- src/interfaces/IERC20.sol
- src/interfaces/IERC4626.sol
- src/interfaces/IERC721.sol
Closes #192 
When an EIP had a solidity interface with comments I pasted that directly, otherwise I took the OZ interfaces and truncated them a bit. In all cases I made the natspec style consistent
Includes an unrelated visibility change for bound
Merging into the v0.3 branch since that should get merged soon
> feat: add interfaces

- src/StdUtils.sol
- test/StdUtils.t.sol
Check programmatically that wrapped `bound` results are evenly distributed.
- Add a test
- Fix solc warning for `_bound` unassigned return
> test(bound): add even distribution test

- src/interfaces/IERC1155.sol
- src/interfaces/IERC4626.sol
- src/interfaces/IERC721.sol
For some strange and frustrating reason, importing from a submodule that uses absolute imports from a common directory name seems to break Solidity linting in VSCode – even though the code compiles and runs fine. I've tried with both Juan Blanco and Hardhat Solidity extensions.
Here's an example code block:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;
import {Test} from "forge-std/Test.sol";
import {IERC721} from "forge-std/interfaces/IERC721.sol";
contract LintingTest is Test {
function testTransact() public {
// address payable receiver = payable(0);
receiver.transfer(1 ether);
}
}
```
Obviously, this won't compile as-is - but the linter (probably?) doesn't show any errors, either. Uncommenting the `receiver` declaration results in it compiling just fine.
Using …
> Use relative imports in interfaces for VSCode linting compatibility

- src/Vm.sol
Many cheats should be view/pure. When you build tooling on top of cheats it's nice to be able to use regular view/pure modifiers.
edit: I haven't restricted the mutability of cheats that change the evm state, the environment, the file system, or the cheat interpreter state (eg `getRecordedLogs` stops recording so it's not `view`).
> restrict cheats mutability

- src/StdAssertions.sol
- src/StdJson.sol
- src/Test.sol
- Changes ds-test imports back to absolute paths, per #208 
- Updates visibility to remove compiler warnings, which resulted from #205
> fix: ds-test imports + compiler warnings

- src/Vm.sol
add ```emitter``` field to ```Log``` struct for foundry [PR #3639](https://github.com/foundry-rs/foundry/pull/3639) compatibility
> feat: add emitter to Log struct

- src/StdUtils.sol
This is not causing a bug because it's expected that if `x < max` then `x < min` thanks to the condition met earlier in the function's execution: `x < min || x > max` (otherwise it would have returned `x`)
But this PR is for code clarity
> Fix unexpected condition in `bound`

- src/interfaces/IERC1155.sol
The interface in `IERC1155.sol` is named `ERC1155`, rather than `IERC1155` 
Unfortunately this a breaking change; we could also include `interface ERC1155 is IERC1155 {}` for backwards compatibility?
> Fix IERC1155 Interface name

- src/StdCheats.sol
Allow tests to easily change behavior (or be skipped) when running in forking or non-forking mode
Adds convenience methods to `StdCheats`:
- `isFork` - returns the current forking status
- `skipNonForking` - run only when forked 
- `skipForking` - run only when not forked
> feature: isFork and skip modifiers in StdCheats

- .github/workflows/ci.yml
- prints forge version to simplify reproducing CI failures
- deps are installed automatically, so an explicit step for them is not needed
> ci: print forge version in CI

- src/Components.sol
- src/Script.sol
- src/StdChains.sol
- src/StdCheats.sol
- src/Test.sol
- src/Vm.sol
- test/StdChains.t.sol
- test/StdCheats.t.sol
Resolve #225, #232
Lazy-initialize chains.
Tested on [Uniswap / permit2](https://github.com/Uniswap/permit2). Takes the same time to compile as the pre-V1 Forge-Std version used there.
@marktoda, could you please test the changes on your end?
- Add `StdChains` Component
- **BREAKING:** Add `getChain` and `setChain` functions
- **BREAKING:** `Vm.Rpc.name` -> `Vm.Rpc.key`
@mds1, please let me know what you think about the design decisions.
> feat: reimplement `StdChains`

- src/StdCheats.sol
Do not include `StdChains` in `StdCheatsSafe` (and `StdCheats`), because it breaks modularity.
Hardcode the chain IDs in `assumeNoPrecompile` instead of calling `getChain`.
This is safe because chain IDs will rarely (if ever) change.
> fix: remove `StdChains` from `StdCheatsSafe`

- src/StdCheats.sol
- src/Vm.sol
- test/StdCheats.t.sol
Adds support for `pauseGasMetering` and `resumeGasMetering` to `VmSafe`.
Additionally adds a modifier: `noGasMetering`, that pauses gas metering during the function's execution and resumes afterward (allows for nested `noGasMetering` function calls).
Depends on
https://github.com/foundry-rs/foundry/pull/3826
> feat: Add gas metering cheatcodes + modifier

- src/Vm.sol
Now after https://github.com/foundry-rs/foundry/pull/3810 is merged - we can add the new envOr cheatcode to the Vm interface at forge-std.
> feat: add envOr cheatcodes to Vm interface #3732

- src/Vm.sol
Benefits:
1. Enable Forge Std users to call cheatcodes with [named arguments](https://twitter.com/PaulRBerg/status/1574071928544976896), which improves readability.
2. Better documentation for people who read the source code.
Examples:
```solidity
vm.roll({ newHeight: block.height + 100 });
vm.getCode({ path: "../../path/to/MyContract.sol" });
vm.expectEmit({ checkTopic1: true, checkTopic2: true, checkTopic3: true, checkData: true });
```
I think that this is especially useful for the `expectEmit` cheatcode, which, to quote the [Foundry Book](https://book.getfoundry.sh/forge/cheatcodes), is known for being "non-intuitive".
Notes:
- Generally I have tried to follow the argument names suggested in the comments
- When there was no name suggestion in the comments, I came up with my own …
> Name arguments in Vm.sol

- src/StdUtils.sol
- src/console2.sol
- test/StdCheats.t.sol
- test/StdUtils.t.sol
Implementing `boundInt(int256,int256,int256)` at StdUtils.sol to help fuzzing test with integer arguments.
One problem is that `log(string,int256)` does not exist so I used `log(string,uint256)` instead of it.
> feat: implement boundInt

- src/StdCheats.sol
- src/Vm.sol
There are currently compiler warnings when using Forge Std v1.2.0:
```text
lib/forge-std/src/Vm.sol:39:62: Warning: This declaration shadows an existing declaration.
function addr(uint256 privateKey) external pure returns (address addr);
^----------^
lib/forge-std/src/Vm.sol:39:5: The shadowed declaration is here:
function addr(uint256 privateKey) external pure returns (address addr);
^---------------------------------------------------------------------^
lib/forge-std/src/Vm.sol:166:64: Warning: This declaration shadows an existing declaration.
function rememberKey(uint256 privateKey) external returns (address addr);
^----------^
lib/forge-std/src/Vm.sol:39:5: The shadowed declaration is here:
function addr(uint256 privateKey) external pure returns (address addr); …
```
> Fix compiler warnings

- src/InvariantTest.sol
Add functions for:
- Excluding target contracts `excludeContract`
- Excluding sender addresses `excludeSender`
- Adding target contracts `targetContract`
- Adding target senders `targetSender`
- Adding target selectors `targetSelector`
- View functions for all arrays
> feat: Add `InvariantTest` contract

- src/InvariantTest.sol
Incorporating feedback from https://github.com/foundry-rs/forge-std/pull/261
> feat: Update `InvariantTest` inheritance, add new functions, fix CI [WIP]

- src/InvariantTest.sol
- Update all array visibilities to private.
- Reorder functions to group user functions and forge-specific functions.
- Remove require statements in view functions.
> fix: `InvariantTest` cleanup

- src/StdAssertions.sol
- test/StdAssertions.t.sol
Adding decimal formatting support for the `assertApproxEqAbs` assertions. Since it's a small one I figured I'd just PR instead of opening an issue, let me know if I need to create one
> feat: add assertApproxEqAbsDecimal assertions

- src/StdChains.sol
- test/StdChains.t.sol
Ping @mds1
Two useful updates to the `StdChains`.
1. Adds the `chainAlias` to the`Chain` struct. We need access to this as the chain alias is useful for defining chain-specific stuff inside configuration json files such as:
```
{
"domains": {
"mainnet": {
"chainlog": "0xdA0Ab1e0017DEbCd72Be8599041a2aa3bA7e740F"
},
"optimism": {
"l1Messenger": "0x25ace71c97B33Cc4729CF772ae268934F7ab5fA1",
"l2Messenger": "0x4200000000000000000000000000000000000007"
},
"arbitrum_one": {
"inbox": "0x4Dbd4fc535Ac27206064B68FfCf827b0A60BAB3f",
"arbSys": "0x0000000000000000000000000000000000000064"
}
}
}
```
This is nicer to define than using chain ids.
2. Allow automatic environment variable overrides via `ALIAS_RPC_URL`. For example a user can define `MAINNET_RPC_URL` to set the mainnet rpc url.
This saves …
> Usability Updates for StdChains

- src/StdUtils.sol
- src/interfaces/IMulticall3.sol
- test/StdUtils.t.sol
As discussed in #266, this PR adds the `IMulticall3` interfaces in this repo (hardcoded, not imported from anywhere else). This PR also adds a `getTokenBalances` util in `StdUtils`, which I think will prove quite useful to Multicall users.
Note: I did not write tests for `getTokenBalances` just yet. Not sure if you are happy to merge the PR as is, or you would rather want me/ us to test it first.
> feat: add "IMulticall3" interface

- src/StdUtils.sol
- test/StdUtils.t.sol
- computeCreate2Address(bytes32 salt, bytes32 initCodeHash) returns an address using the default create2 deployer
- hashInitCode(bytes, bytes) and hashInitCodeNoConstructorArgs(bytes) make it more convenient to figure out the init code hash in deploy scripts
> Add create2 helper methods

- src/StdCheats.sol
Changing the `who` arg to `msgSender` would keep the util/ cheat signatures consistent between `StdUtils.sol` and `Vm.sol` (as per the changes introduced in #246).
> refactor: rename "who" arg to "msgSender"

- src/StdChains.sol
- test/StdChains.t.sol
Added a flag to disable falling back to default RPC URLs automatically. Public RPC endpoints are often rate-limited and may result in obscure errors when rate limits are hit. On our team we want to disable this behavior and instead spit out a very clear error that the user does not have the proper environment variable configured.
I've opened it as a draft because the new test is failing because the error is not matching even though I copied it exactly from the console. Is there hidden whitespace or an extra character or something? I don't have time to dig into this atm, so thought I'd submit most of the work.
Ping: @mds1
> Add flag disable default rpc

- src/StdAssertions.sol
This PR changes the `Expected` and `Actual` logs for `assertEq` functions in `StdAssertions.sol` to that of `Left` and `Right`, respectively. 
This is done to match the [assert_eq](https://doc.rust-lang.org/std/macro.assert_eq.html) macro in Rust and improve readability.
> Rename `StdAssertions.sol` logs

- src/Vm.sol
Sister PR to https://github.com/foundry-rs/foundry/pull/4413
Adds two new variants of the expectCall cheatcode that allows for asserting the amount of gas passed to a call.
```solidity
// Expect a call to an address with the specified msg.value, gas, and calldata.
function expectCall(address callee, uint256 msgValue, uint64 gas, bytes calldata data) external;
// Expect a call to an address with the specified msg.value and calldata, and a *minimum* amount of gas.
function expectCallMinGas(address callee, uint256 msgValue, uint64 minGas, bytes calldata data) external;
```
> feat(Vm): Add new `expectCall` variants

- src/StdStyle.sol
- src/Test.sol
- test/StdStyle.t.sol
After discussing with @mds1 and thanks to his help I've created an "styles" library that allows to use `console.log()` with different styles. As intended in #295.
Syntax is `StdStyle.[style_name]("Message")`. This must be used inside the standard console2.log(), and can be used with **string, uint256, int256, boolean and address** types. Moreover, they **can be nested** to apply multiple styles. Eg:
```solidity
console2.log(StdStyle.red("Red Bold String Test"));
console2.log(StdStyle.green(StdStyle.dim(uint256(10e18))));
console2.log(StdStyle.yellow(StdStyle.bold(int256(-10e18))));
console2.log(StdStyle.blue(StdStyle.underline(address(0))));
console2.log(StdStyle.magenta(StdStyle.reverse(true)));
```
- ![#ff0000](https://placehold.co/15x15/ff0000/ff0000.png) `red`
- …
> Added StdStyle library to print logs with different colors and styles

- src/StdAssertions.sol
- test/StdAssertions.t.sol
Adds new assertions to StdAssertions.sol. These are useful for differential fuzz-testing calls.
Expects two calls to either return the same data or revert in the same way (if `strictRevertData = true`).
```solidity
function assertEqCall(
address targetA,
bytes memory callDataA,
address targetB,
bytes memory callDataB,
bool strictRevertData
) internal virtual;
```
> feat(StdAssertions): Add `assertEqCall`

- src/StdCheats.sol
- test/StdCheats.t.sol
I've created the deal cheatcode for ERC721 and ERC1155 tokens.
For ERC721 and it shares the same function signature as ERC20 i've modified the name to dealNft(), this could be merged into a single deal function by checking the interface of the given contract but I'm not sure it is the best option as it would increase gas usage and could lead to more errors for non-standard implementations.
Usage:
```solidity
// ERC721
dealNft(nftAddress, bob, tokenId);
//ERC1155
deal(1155address, bob, id, amount);
deal(1155address, bob, id, amount, true); // Will check if it is ERC1155Supply and adjust totalSupply.
```
> Added deal cheat for ERC721 and ERC1155

- src/StdCheats.sol
- test/StdCheats.t.sol
Adds a `changePrank` invariant that accepts a new parameter `tx.origin` for changing the `msg.sender` and the `tx.origin` at the same time.
> feat: add "changePrank" variant

- src/StdCheats.sol
- src/Vm.sol
Implements https://github.com/foundry-rs/forge-std/issues/252.
I know that this has been previously discussed in https://github.com/foundry-rs/forge-std/pull/42, but I think that this abstraction would be so helpful that it's worth reconsidering it.
FWIW: I have this function defined in like ~7 separate repos.
> feat: add simple "expectEmit"

- src/Vm.sol
In #320, I forgot to name the `emitter` argument.
> feat: name emitter in "expectEmit"

- test/StdAssertions.t.sol
As title. This removes the current compiler warnings:
```bash
Compiler run successful (with warnings)
warning[5667]: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
--> contracts/lib/forge-std/test/StdAssertions.t.sol:923:9:
|
923 |         bytes memory returnDataA,
|         ^^^^^^^^^^^^^^^^^^^^^^^^
warning[5667]: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
--> contracts/lib/forge-std/test/StdAssertions.t.sol:9[24](https://github.com/pcaversaccio/hardhat-project-template-ts/actions/runs/4446205270/jobs/7806238050#step:10:25):9:
|
924 |         bytes memory returnDataB,
|
```
> ♻️ Remove Unused Function Parameters in `StdAssertions.t.sol`

- test/StdAssertions.t.sol
PR to increment version of DS test (as suggested: https://github.com/foundry-rs/foundry/issues/4634)
* I've ran a `forge install` against DS Test and bumped to the latest commit on master there
* I've added some test cases into `StdAssertions.t.sol` and tried to match the conventions there
* Ran `forge fmt` and `forge test` (passes).
Please let me know any suggestions/amends.
> Increment DS Test version

- src/StdUtils.sol
Discovered this `todo` comment in `src/StdUtils.sol` that seems out of place. Unless this is here for a reason, I suggest removing it.
> fix: removed unnecessary todo comment

- src/Vm.sol
> feat: add count to `expectCall` cheatcodes

- test/StdChains.t.sol
`testRpcs` often takes ~50 mins and fails due to flaky public RPCs. Temporarily commenting it out for now until we find a better solution. Tracking in https://github.com/foundry-rs/forge-std/issues/363
> test: comment out flaky test

- .github/workflows/sync.yml
Adds a CI workflow for syncing the `v1` branch every time a new git tag that starts with `v1` is pushed to remote.
> ci: sync release branch

- src/console2.sol
- test/StdStyle.t.sol
h/t @0age https://twitter.com/z0age/status/1654922202930888704
Thought about creating a different console3.sol but there is no downside to just making everything pure.
> feat: pure `console.log`s

- src/safeconsole.sol
Adds a new alternative logging library to `console` and `console2`, dubbed "safeconsole" that behaves almost identically to `console2` but leaves memory intact, making it useful for logging and debugging memory manipulating inline-assembly code. This is achieved by replacing string arguments with `bytes32` allowing you use the same string-syntax e.g. `safeconsole.log("My int: %d", 34);` without affecting memory (as long as your logging string is less than or equal to 32 characters long). The library also uses the [0age function pointer casting trick](https://twitter.com/z0age/status/1654922202930888704) to ensure that all logging functions are `pure` and don't require function visibility changes.
Carried over from my repo [forge-safe-log](https://github.com/Philogy/forge-safe-log) …
> feat: add memory safe logging

- src/Base.sol
Useful when fuzzing private keys, e.g.
```solidity
function test_Something(uint256 privateKey) external {
privateKey = bound(privateKey, 1, SECP256K1_ORDER - 1);
}
```
> feat: add "SECP256K1_ORDER" constant

- src/StdUtils.sol
- test/StdUtils.t.sol
This PR adds a utility for bounding private keys between 1 and the SECP256k1 order minus 1.
As shown by the discussions in https://github.com/foundry-rs/foundry/issues/3031, it is not obvious that private keys have to be bounded between 1 and the curve order minus 1.
Note: I used the console log-free `_bound` due to security reasons (avoiding accidental leaks of private keys).
> feat: add "boundPrivateKey" util

- src/StdCheats.sol
Unless I'm missing something, `staticcall` should be used instead of `call` for querying the token balances.
Cc @brockelmore.
> perf: use staticcall instead of call

- src/StdCheats.sol
- src/Vm.sol
- test/StdCheats.t.sol
Introduces a new std cheatcode, `destroyAccount`, which mimics `SELFDESTRUCT` behavior. 
This is a companion PR to the one that introduces `resetNonce` to Forge itself: see the [Forge PR](https://github.com/foundry-rs/foundry/pull/5033) for rationale.
> add: destroyAccount cheatcode

- src/StdCheats.sol
- test/StdCheats.t.sol
Implements #380.
Btw, while writing the tests for this, I was looking at [`testAssumePayable`](https://github.com/foundry-rs/forge-std/blob/20872c5b1900526579159bdc6967f6b48c22e50e/test/StdCheats.t.sol#L319-L333) and wondering why it works?
I thought that `vm.expectRevert` only works for external reverts?
> feat: add "assumeNoBlacklisted" cheat

- .github/workflows/ci.yml
Resolve #402 
Fail CI if there's `Warning` in output.
> ci: check for warnings

- src/StdCheats.sol
- test/StdCheats.t.sol
There's `vm.etch`, which sets the _runtime_ bytecode on an _arbitrary_ address, and `deployCode`, which takes a _creation_ code, and returns the _deployment_ address.
However, there's no option in-between.
`deployCodeTo` lets you pseudo-deploy a contract from its _creation_ code on an _arbitrary_ address.
> feat(cheats): `deployCodeTo`

- src/Vm.sol
Downstream from https://github.com/foundry-rs/foundry/pull/5205
Adds and documents the new `vm.skip(bool)` cheatcode.
> feat: add vm.skip(bool)

- src/StdStorage.sol
- test/StdStorage.t.sol
There is no `checked_write` function for `int256` param.
There are only `checked_write` functions with `address`, `uint256`, `bool` and `bytes32` parameters now.
Actually, for `int256` variables, the below code can be used.
```
int256 value = -100;
stdstore
.target(address(addr))
.sig("var()")
.checked_write(uint256(value));
```
But it might be better if it has `checked_write` function for `int256` params since the above code is not good to understand.
> Add checked_write_signed for int256

- src/StdCheats.sol
- test/StdCheats.t.sol
Excludes the `vm` address `0x7109709ECfa91a80626fF3989D68f67F5b1DD12D` from the `assumeNoPrecompiles` cheat code. 
Resolves #405 
Note that `address(vm)` is used instead of `address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D)` (such as in  `testAssumePayable`) so that it fits squarely into the current implementation of the cheat code and respective test with minimal confusion. Open to changing this though.
> feat: Refactor `assumeNot*` std cheats

- src/Script.sol
- src/Test.sol
https://github.com/foundry-rs/foundry/pull/5404
- Remove warning note
- Restore inheritance order
> fix: restore inheritance order

- src/Vm.sol
Adds parseJsonKeys cheatcode created in https://github.com/foundry-rs/foundry/pull/5252
> Add parseJsonKeys

- src/Vm.sol
Upstream from https://github.com/foundry-rs/foundry/pull/5431
> feat(`vm`): add keyExists

- src/StdCheats.sol
Leftover work from https://github.com/foundry-rs/foundry/pull/4826#issuecomment-1543962477 — deprecates `changePrank` before we delete it completely.
> chore(`StdCheats`): deprecate changePrank

- src/StdCheats.sol
- test/StdCheats.t.sol
`assumeNotForgeAddress` allowed any address to pass the assumption check. Unless `address(vm) == 0x000000000000000000636F6e736F6c652e6c6f67` (which is not), the condition always pass.
- Fixed by changing logical `or` to `and` in the condition. 
- Add check for Create2Deployer address
> Fix assumeNotForgeAddress in StdCheats.sol

- test/StdAssertions.t.sol
- test/StdChains.t.sol
- test/StdCheats.t.sol
- test/StdError.t.sol
- test/StdMath.t.sol
- test/StdStorage.t.sol
- test/StdStyle.t.sol
- test/StdUtils.t.sol
This PR puts the `forge-std` test naming conventions in line with the [style guide](https://book.getfoundry.sh/tutorials/best-practices#tests)
Some liberties have been taken with respect to the names in `StdAssertions.t.sol` but open to any feedback.
I did not add any test names with the `Revert[If|When]` modifier since none of the tests appear to pass or fail conditionally. Correct me if this is erroneous. 
Closes #273
> chore: conform test naming to style guide

- src/StdChains.sol
- test/StdChains.t.sol
Updates StdChains to have base and base goerli as default rpcs during initialization
> feat: base goerli and base chaindata setup to stdchains default rpcs

- src/StdJson.sol
- src/Vm.sol
Hi folks, I believe the json parsing cheatcodes classify as pure as they are not affected by other calls and don't read the state. Please let me know if I'm missing anything.
> chore: make json parse cheatcodes pure

- src/Vm.sol
See https://github.com/foundry-rs/foundry/pull/5123/files
> feat(`vm`): add mapping slot cheatcodes

- src/StdStorage.sol
- test/StdStorage.t.sol
When finding the target slot ID of a function signature, `find()` would do a staticcall and iterate over all the possible slots, then set the slot to a hardcoded value `hex"1337"` to test if the slot is desired.
But if there are multiple slot reads in the function call and the desired slot value is set to `hex"1337"` coincidentally, a wrong slot id may be returned.
Minimal reproduce contract:
```solidity
import "forge-std/Test.sol";
import "forge-std/StdStorage.sol";
contract StorageTest {
bytes32 public a = hex"abcd";
bytes32 public b = hex"1337";
function extraSload() public view returns (bytes32) {
// trigger read on slot `a`, and make a staticcall to make sure compiler doesn't optimize this SLOAD away
assembly {
pop(staticcall(gas(), sload(a.slot), 0, 0, 0, 0))
}
return b;
}
function …
```
> fix(stdStorage): wrong slot id may returned by `find()` when slot value == 1337

- src/StdJson.sol
- src/Vm.sol
Adds the new serializeJson cheatcode to the Vm and updates StdJson. Foundry's PR: https://github.com/foundry-rs/foundry/pull/5755
I didn't add tests because it just calls the vm and there are no tests for StdJson. Let me know if I should add some.
> feat: add new serializeJson cheatcode to the Vm and to StdJson

- src/Vm.sol
Pardon my OCD but I am getting a Solhint warning in my copy of `Vm` (in PRBTest) because of `exit_code`:
> warning  Variable name must be in mixedCase  var-name-mixedcase
> chore: camelCase for exitCode

- src/Vm.sol
Following https://github.com/foundry-rs/foundry/pull/5952.
Adding `vm.unixTime()` cheatcode to `VmSafe` interface.
I tested this change manually on my machine.
> Add vm.unixTime to VmSafe interface

- src/StdChains.sol
- test/StdChains.t.sol
Rely less on internal Foundry error messages for our own testing.
Unfortunately it looks like we still rely on the "RPC URL not found" error message to when defaulting to environment variables in `StdChains.getChainWithUpdatedRpcUrl`.
Unblocks https://github.com/foundry-rs/foundry/pull/6131
cc @mattsse @mds1
> fix: rely less on foundry internals

- src/Vm.sol
- test/Vm.t.sol
Adds the `loadAllocs(string)` cheatcode to be usable as part of the
`Vm` interface. This was added to foundry in https://github.com/foundry-rs/foundry/pull/6207.
The cheatcode can be used to read a JSON file from disk that sets EVM
state directly.
> vm: add `loadAllocs(string)` cheatcode

- src/Vm.sol
- test/Vm.t.sol
These were the last missing cheats added in the past month to Foundry.
> feat(`vm`): add rpc and eth_getLogs cheats

- src/Vm.sol
- test/Vm.t.sol
Follow up on https://github.com/foundry-rs/foundry/pull/6310 to expose the newly added cheats, `startStateDiffRecording` and `stopAndReturnStateDiff`, to the `VmSafe` interface.
> feat: add storage and access record cheats

- src/StdChains.sol
- src/Vm.sol
- test/StdUtils.t.sol
In https://github.com/foundry-rs/foundry/pull/6757, we marked the `envOr` functions as view functions. Updating equivalent function signatures here
Code diff is essentially the same as previous attempt https://github.com/foundry-rs/forge-std/pull/490, except this time I generated `Vm.sol` the correct way by running the `scripts/vm.py` script
`forge compile` and `forge test` still pass
> Codegen Vm.sol to mark envOr functions as view

- src/Vm.sol
- test/Vm.t.sol
Adds a new cheatcode `dumpState(string)` that was implemented in foundry in https://github.com/foundry-rs/foundry/pull/6827. This cheatcode will write a JSON file to disk that contains the current state of the EVM.
> vm: add dumpState cheatcode

- scripts/vm.py
https://github.com/foundry-rs/foundry/pull/6841 introduced `internal` cheatcodes type for cheats only used internally for foundry testing. Such cheatcodes shouldn't end up in forge-std. 
This PR updates `vm.py` script to exclude them along with `experimental` cheats
> Exclude internal cheats from Vm

- src/StdJson.sol
Fixed minor typo in `StdJson.sol` (`some_peth` -> `some_path`)
`eth` on the brain, I get it :joy:
> Fix typo in `StdJson.sol` usage comments

- src/StdStorage.sol
- test/StdCheats.t.sol
- test/StdStorage.t.sol
This was initially designed to fix probles with USDC, but it seems that we are now able to modify pretty much any packed storage variables.
This is still a WIP as I believe binary operations can be rewritten a bit cleaner but it already works.
I've updated some of the negative tests on failing packed variables decoding to being positive.
The solution is to try finding such `offsetLeft` and `offsetRight` for a storage slot, that it's `value[offsetLeft:-offsetRight]` exactly equals the return data of the given function
> stdStorage: support packed variables

- test/StdChains.t.sol
I don't think there's a way to make this pass either, so I'm removing it.
> test: remove test marked as internal

- foundry.toml
- src/StdChains.sol
- src/Test.sol
- test/StdChains.t.sol
Closes https://github.com/foundry-rs/forge-std/issues/522
This used to come from [ds-test](https://github.com/dapphub/ds-test/blob/e282159d5170298eb2455a6c05280ab5a73a4ef0/src/test.sol#L38C5-L38C32), and v1.8.0 of forge-std removed that dependency
> fix: add `IS_TEST = true` to Test

- .github/workflows/ci.yml
update to correct foundry github action repo  
add identifier to compat checks
Also, shouldn't the Via-IR compilation time checks use the latest solc?
> ci(github): update CI workflow

- .github/workflows/ci.yml
Reverts foundry-rs/forge-std#526
> The workflow is not valid. .github/workflows/ci.yml (Line: 38, Col: 13): The identifier '0.8.0' is invalid. IDs may only contain alphanumeric characters, '_', and '-'. IDs must start with a letter or '_' and and must be less than 100 characters. .github/workflows/ci.yml (Line: 49, Col: 13): The identifier '0.7.6' is invalid. IDs may only contain alphanumeric characters, '_', and '-'. IDs must start with a letter or '_' and and must be less than 100 characters.
@sambacha any chance you can reopen with fixed identifiers? not sure why this didn't fail on the PR itself
> Revert "ci(github): update CI workflow"

- src/Vm.sol
- test/Vm.t.sol
Following https://github.com/foundry-rs/foundry/pull/7012.
Adding the `vm.prompt` and `vm.promptSecret` cheatcodes to the `Vm.sol` interface.
Fixes #528
> Add `vm.prompt` cheatcodes to Vm interface

- src/StdUtils.sol
Make the logs for `bound(uint256 x, uint256 min, uint256 max)` and `bound(int256 x, int256 min, int256 max)` consistent.
> chore: fix bound log

- src/StdChains.sol
- test/StdChains.t.sol
As Polygon is deprecating Mumbai testnet and preferring the new testnet, Amoy. We are adding supports for Amoy accordingly in the implementation and test file.
Reference:
1. [Polygon Blog]((https://polygon.technology/blog/introducing-the-amoy-testnet-for-polygon-pos))
> feat: Add support for polygon amoy testnet

- src/StdInvariant.sol
The return type of `targetArtifactSelector` is `(string, bytes4[])[]`.
See: <https://github.com/foundry-rs/foundry/blob/db8ea58ba607075ce0f39bb975a38da6b4889ea1/crates/evm/evm/src/executors/invariant/mod.rs#L377-L379>
> fix(StdInvariant): correct `targetArtifactSelector` type

- src/mocks/MockERC721.sol
Removes a duplicate interface.
I was running into:
with a newly created foundry repo that only had `Counters.sol` in the src directory. It seems to have been caused by the duplicate IERC721TokenReceiver interfaces
> chore: remove duplicate interface

- src/Vm.sol
- test/Vm.t.sol
Following https://github.com/foundry-rs/foundry/pull/8082, this PR adds `promptSecretUint(string)(uint)` cheatcode to Vm interface.
~PS: I ran vm.py and it results in the interface being out of date with `randomAddress()(address)`, `randomUint()(uint)` & `randomUint(uint,uint)(uint)` methods, let me know if you'd prefer to just include them in this PR.~ nvm, saw 562.
> feat(cheatcode): promptSecretUint

- src/console.sol
Ref https://github.com/foundry-rs/forge-std/pull/573#issuecomment-2203315762
I copy pasted the console2 functions to console and replaced `int256` with `int`.
This is the entire diff.
> fix: add missing console logs

- src/StdStorage.sol
- test/StdStorage.t.sol
simple optimization which resolves https://github.com/foundry-rs/forge-std/issues/580 and optimizes slots detection in some cases
It is more likely that slot we are looking for will be one of latest sloads. e.g. if execution went like
```
sload slot_1 <- currently we start from here
sload slot_2
sload slot_3 <- in most of the cases this value is returned
return
```
so this PR simply changes order in which we go through `vm.accesses` output
> fix(StdStorage): check last read slots first

- src/StdCheats.sol
After the cancun hardfork, the point evaluation precompile was added at `address(10)` which the `assumeNotPrecompile` implementation did not take into account. Pectra is scheduled to include BLS precompiles and likely more precompiles will be introduced in other future hardforks. We might as well reserve the least significant byte for Ethereum precompiles, as the address space is large and there is no need to make calls from these addresses, and in return code will not break on new EVM specs.
This was causing test failures in the Optimism test suite when we updated the EVM version to cancun.
> cheats: fix assume not precompile

- src/Vm.sol
- test/Vm.t.sol
re https://github.com/foundry-rs/foundry/pull/8807
> feat: setArbitraryStorage, copyStorage, mockFunction and assumeNoRevert

- src/StdJson.sol
- src/StdToml.sol
Hey @zerosnacks @klkvr can I get a quick review here?
One thing I'm wondering: why are the `keyExists` cheats `view` but the other JSON/TOML parsing cheats are `pure`?
> feat: add keyExists to stdJson and stdToml

- src/console.sol
Both Hardhat and Foundry have supported the correct console.log internal signatures for a few years now, and Hardhat is currently looking to remove support for the incorrect signatures entirely. See https://github.com/NomicFoundation/hardhat/pull/5764.
Note that our console.sol has 2 additional functions for `log(int256)` and `log(string,int256)` inherited from `console2`, which were added in https://github.com/foundry-rs/forge-std/pull/253.
> feat(console): use correct signatures

- src/Vm.sol
- test/Vm.t.sol
Includes:
- `getArtifactPathBy{,Deployed}Code`
- `parseTomlType`
- `expect{,Partial}Revert(..., address)`
- `skip(bool, string)`
- `random{Bool,Bytes,Int}`
I've also split the `interfaceId` test into two so that you can get both values to update at once.
Supersedes https://github.com/foundry-rs/forge-std/pull/608.
> feat(Vm): add new cheatcodes

- src/Vm.sol
- test/Vm.t.sol
The latest version of Foundry emits a deprecation warning users encounter if they are using the deprecated snapshot cheatcodes
Related PR: https://github.com/foundry-rs/foundry/pull/8945
Ref: https://github.com/foundry-rs/foundry/pull/8945#issuecomment-2385266819
> fix: update snapshot cheatcodes

- src/Vm.sol
- test/Vm.t.sol
Added methods for `vm.mockCalls` in `Vm` interface, see https://github.com/foundry-rs/foundry/pull/9024.
> Update Vm.sol with vm.mockCalls methods

- src/Vm.sol
- test/Vm.t.sol
Run script/vm.py to update the cheatcode.
Mainly to enable for this new cheatcodes for debug trace recording: https://github.com/foundry-rs/foundry/pull/8571
> feat(Vm): update cheatcode by vm.py

- CONTRIBUTING.md
- README.md
Closes:  https://github.com/foundry-rs/forge-std/issues/117 
- Add note on testing across compiler version targets locally
- Updates links to point to `choose` panels to enforce issue / discussion templates
> chore: add guidance on running compatibility checks locally

- src/Vm.sol
- test/Vm.t.sol
Companion PR for https://github.com/foundry-rs/foundry/pull/9087
Adds two new cheatcodes to the vm interface: 
```solidity
function rememberKeys(string calldata mnemonic, string calldata derivationPath, uint32 count) external returns (address[] memory keyAddrs);
function rememberKeys(string calldata mnemonic, string calldata derivationPath, string calldata language, uint32 count) external returns (address[] memory keyAddrs);
```
> feat(`vm`): rememberKeys

- src/Vm.sol
- test/Vm.t.sol
Companion PR for https://github.com/foundry-rs/foundry/pull/9052
Adds the cheatcode `function getWallets() external returns (address[] memory wallets)`
> feat: `vm.getWallets()`

- src/Vm.sol
- test/Vm.t.sol
Add cheatcodes introduced in https://github.com/foundry-rs/foundry/pull/9107.
```solidity
// Returns the most recent broadcast for the given contract on `chainId` matching `txType`.
function getBroadcast(string memory contractName, uint64 chainId, BroadcastTxType txType) external returns (BroadcastTxSummary memory);
//  Returns all broadcasts for the given contract on `chainId` with the specified `txType`.
//  Sorted such that the most recent broadcast is the first element, and the oldest is the last. i.e descending order of BroadcastTxSummary.blockNumber.
function getBroadcasts(string memory contractName, uint64 chainId, BroadcastTxType txType) external returns (BroadcastTxSummary[] memory);
// Returns all broadcasts for the given contract on `chainId`.
// Sorted such that the most …
```
> feat(`vm`): get broadcasts

- src/Vm.sol
- test/Vm.t.sol
Ref: https://github.com/foundry-rs/foundry/pull/9267
Adds the following overloads for `vm.mockCall`. 
```solidity
function mockCall(address callee, bytes4 data, bytes calldata returnData) external;
function mockCall(address callee, uint256 msgValue, bytes4 data, bytes calldata returnData) external;
function mockCallRevert(address callee, uint256 msgValue, bytes4 data, bytes calldata revertData) external;
function mockCallRevert(address callee, bytes4 data, bytes calldata revertData) external;
```
> feat: mockCall overloads

- test/StdChains.t.sol
There are no stability guarantees about error messages.
This specific error message was changed in https://github.com/foundry-rs/foundry/pull/9353.
> test: don't expect a specific cheatcode error message

- src/Vm.sol
- test/Vm.t.sol
- add `delegatecall` flag to `prank` cheatcodes (https://github.com/foundry-rs/foundry/pull/8863)
- support EIP-7702 Delegations (`create/sign/attachDelegation`) (https://github.com/foundry-rs/foundry/pull/9236)
- add `contains` to check if a string contains another string (https://github.com/foundry-rs/foundry/pull/9085)
> Update to latest cheatcodes

- src/Vm.sol
- test/Vm.t.sol
Ref: https://github.com/foundry-rs/foundry/pull/9484
```solidity
/// Expects `count` number of reverts from the upcoming calls with any revert data or reverter.
function expectRevert(uint64 count) external;
/// Expects `count` number of reverts from the upcoming calls that match the revert data.
function expectRevert(bytes4 revertData, uint64 count) external;
/// Expects `count` number of reverts from the upcoming calls that exactly match the revert data.
function expectRevert(bytes calldata revertData, uint64 count) external;
/// Expects `count` number of reverts from the upcoming calls from the reverter address.
function expectRevert(address reverter, uint64 count) external;
/// Expects `count` number of reverts from the upcoming calls from the reverter address that match the revert …
```
> feat: `count` assertion for `expectRevert` 

- src/Vm.sol
- test/Vm.t.sol
Ref: https://github.com/foundry-rs/foundry/pull/9405
Adds the following cheatcodes to the interface:
```solidity
/// Expect a given number of logs with the provided topics.
function expectEmit(bool checkTopic1, bool checkTopic2, bool checkTopic3, bool checkData, uint64 count) external;
/// Expect a given number of logs from a specific emitter with the provided topics.
function expectEmit(
bool checkTopic1,
bool checkTopic2,
bool checkTopic3,
bool checkData,
address emitter,
uint64 count
) external;
/// Expect a given number of logs with all topic and data checks enabled.
function expectEmit(uint64 count) external;
/// Expect a given number of logs from a specific emitter with all topic and data checks enabled.
function expectEmit(address emitter, uint64 count) external;
> feat: count assertions for expectEmit

- README.md
The issue arises because the variable `a` is already declared as a parameter of the `arithmeticError` function:
```solidity
function arithmeticError(uint256 a) public {
uint256 a = a - 100; // Error: `a` is already declared as a parameter
}
When you redeclare a with uint256 a = a - 100;, the compiler throws an error because you're trying to shadow the parameter a by declaring a new variable with the same name. This is not allowed in Solidity.
To fix this, simply remove the type declaration (uint256) and use the parameter a directly:
solidity
Code kopieren
function arithmeticError(uint256 a) public {
a = a - 100; // Correct: modifies the existing parameter `a`
}
> Fixing Variable Shadowing in Solidity: uint256 Redeclaration Error

- src/StdCheats.sol
Sometimes during fuzzing we want to test with a wide range of addresses, but these address need to be empty and not already have contracts deployed. This cheatcode would come in handy for that. 
Any suggestions if other overloads are necessary for extended use cases?
> feat: new cheatcode `assumeUnusedAddress`

- foundry.toml
- src/StdChains.sol
- test/StdChains.t.sol
Add: zora, race, metal, binary, orderly and mode testnets and mainnet configs.
> OP Networks Add

- foundry.toml
- src/StdChains.sol
- test/StdChains.t.sol
- test/StdCheats.t.sol
We are running into Alchemy API limits (https://github.com/foundry-rs/forge-std/actions/runs/13545994206/job/37926743447?pr=654) that is causing the CI to block, small refactor to avoid using hardcoded API keys.
> chore: avoid using Alchemy API keys in tests due to limits

- src/Vm.sol
- test/Vm.t.sol
- adds new cheatcodes introduced in 
https://github.com/foundry-rs/foundry/pull/10112
https://github.com/foundry-rs/foundry/pull/10128
- add `cool` by removing Experimental status
- include `expectCreate` / `expectCreate2` and `foundryVersionAtLeast/foundryVersionCmp`
> feat: new accessList, warm/coolSlot. Include cool cheatcode too.

- package.json
In preparation for 1.9.7 release for Foundry v1.1
> chore: bump to 1.9.7

- src/StdAssertions.sol
Avoid calling vm when the condition is trivial to check inline. This is a minor performance improvement as a couple of opcodes execute a lot faster than a full cheatcode pipeline (external call, EVM call bookkeeping, abi encoding/decoding, ...) that eventually does nothing.
For example, [Uniswap's v4-core](https://github.com/Uniswap/v4-core/) spends ~28% of the entire `forge test` CPU time in a couple of trivial `assert` functions (uint256, bytes32, true, false), ~13% for `forge coverage`. This is without accounting for the actual CALL/abi coding etc.
These numbers are skewed due to profiling overhead, however making this change does have ~5% overall test performance improvement, for no compilation time change.
> perf(StdAssertions): avoid vm call for trivial conditions

- src/StdConfig.sol
Corrects a comment typo in `src/StdConfig.sol` for the `writeToFile` parameter.
> StdConfig: fix typo in writeToFile param doc 

- .github/workflows/codeql.yml
This PR introduces CodeQL code scanning initially just focused on Github actions as it is fast to run.
https://docs.github.com/en/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning-with-codeql
Results are reported privately in the `security` tab.
This workflow was derived from the default workflow example Github provides enhanced with concurrency cancel in progress, updated cron to run daily and allow workflow dispatch. Trigger on cron, pull requests and pushes to master.
> chore(`ci`): add CodeQL
